#!/usr/bin/env bash
set -euo pipefail

out_dir="${1:-${OUT_DIR:-build/web}}"
config="${2:-${CONFIG:-Release}}"

usage() {
  cat <<EOF
Usage: scripts/build.sh [out_dir] [Release|Debug]
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "$config" != "Release" && "$config" != "Debug" ]]; then
  echo "Invalid config '$config'. Expected Release or Debug." >&2
  exit 2
fi

if ! command -v em++ >/dev/null 2>&1; then
  echo "em++ was not found in PATH." >&2
  echo "Use scripts/build-docker.sh or scripts\\build-docker.bat." >&2
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if [[ ! -f web/logo.png ]]; then
  echo "Missing web/logo.png." >&2
  exit 1
fi

if [[ ! -f public/NotoSansJP-Regular.ttf ]]; then
  echo "Missing public/NotoSansJP-Regular.ttf." >&2
  exit 1
fi

mkdir -p "$out_dir" src/autogenerated
rm -f "$out_dir"/index.html "$out_dir"/index.js "$out_dir"/index.wasm
rm -f "$out_dir"/th06.html "$out_dir"/th06.js "$out_dir"/th06.wasm
cp web/logo.png "$out_dir/logo.png"
cp -a public/. "$out_dir"/

python3 - <<'PY'
from pathlib import Path

root = Path(".")
out = root / "src" / "autogenerated" / "Embeds.hpp"

def emit(path: Path, name: str) -> str:
    data = path.read_bytes()
    body = "".join(f"0x{byte:02X}, " for byte in data)
    return f"\nstatic char {name}[] = {{{body}0}};\n"

out.write_text(
    "#pragma once\n"
    + emit(root / "src" / "graphics" / "ff.vert", "vertShaderBytes")
    + emit(root / "src" / "graphics" / "ff.frag", "fragShaderBytes"),
    encoding="utf-8",
)
PY

sources=(
  src/AnmManager.cpp
  src/AsciiManager.cpp
  src/BombData.cpp
  src/BulletData.cpp
  src/BulletManager.cpp
  src/Chain.cpp
  src/Controller.cpp
  src/EclManager.cpp
  src/EffectManager.cpp
  src/Ending.cpp
  src/EnemyEclInstr.cpp
  src/EnemyManager.cpp
  src/FileSystem.cpp
  src/GameErrorContext.cpp
  src/GameManager.cpp
  src/GameWindow.cpp
  src/Gui.cpp
  src/ItemManager.cpp
  src/main.cpp
  src/MainMenu.cpp
  src/MidiOutput.cpp
  src/MusicRoom.cpp
  src/Player.cpp
  src/ReplayManager.cpp
  src/ResultScreen.cpp
  src/Rng.cpp
  src/ScreenEffect.cpp
  src/SoundPlayer.cpp
  src/Stage.cpp
  src/Supervisor.cpp
  src/TextHelper.cpp
  src/ZunMath.cpp
  src/utils.cpp
  src/ZunTimer.cpp
  src/graphics/GLFunc.cpp
  src/graphics/FixedFunctionGL.cpp
  src/graphics/WebGL.cpp
  src/graphics/Software.cpp
  src/midi/MidiDefault.cpp
  src/pbg3/FileAbstraction.cpp
  src/pbg3/IPbg3Parser.cpp
  src/pbg3/Pbg3Archive.cpp
  src/pbg3/Pbg3Parser.cpp
  src/thirdparty/sjis_converter.cpp
)

opt="-O2"
debug_flags=(-DNDEBUG)
if [[ "$config" == "Debug" ]]; then
  opt="-O0"
  debug_flags=(-gsource-map -DDEBUG)
fi

em++ \
  -std=c++20 \
  "$opt" \
  -Wall \
  -Wextra \
  -Wno-unused-parameter \
  -Wno-gnu-anonymous-struct \
  -I src \
  -DTH06_WASM_MAINLOOP_AUDIO \
  -sUSE_SDL=2 \
  -sUSE_SDL_IMAGE=2 \
  '-sSDL2_IMAGE_FORMATS=["png","bmp","jpg"]' \
  -sUSE_SDL_TTF=2 \
  -sALLOW_MEMORY_GROWTH=1 \
  -sEXIT_RUNTIME=0 \
  -sFILESYSTEM=1 \
  -sGL_ENABLE_GET_PROC_ADDRESS=1 \
  -sMIN_WEBGL_VERSION=1 \
  -sMAX_WEBGL_VERSION=2 \
  -sFULL_ES2=1 \
  '-sEXPORTED_RUNTIME_METHODS=["callMain","FS"]' \
  --shell-file web/shell.html \
  -o "$out_dir/index.html" \
  "${debug_flags[@]}" \
  "${sources[@]}"

echo "Browser build written to $out_dir"
